//1. Khai báo action
const SET_USER = "SET_USER";
const SET_CART = "SET_CART";
const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
const SET_USERNAME='SET_USERNAME';
export{SET_USER,SET_CART,SET_IS_LOGGED_IN,SET_USERNAME};